# BASICS OF IMAGE PROCESSING USING PYTHON PART 1 (PIL and np)

__WORK ENVIRONMENTS__

    Anaconda
    Python 3
    Spyder
    Jupyter
    
__LIBRARIES USED__

    PIL
    numpy
    OpenCv (cv2)
    Matplotlib
    keras

## VIEWING AN IMAGE

    1) import necessary libraries
        a. numpy
        b. PIL
    
    2) open file location

    3) show image

In [ ]:
import numpy as np
from PIL import Image

FilePath = 'rose.jpg'

img = Image.open(FilePath)

print('Image format: ', img.format)
print('Image mode: ', img.mode)

img.show()

## CONVERT an IMAGE to NP ARRAY

    1) import necessary libraries
    2) convert image format to numpy array
    3) inspect necessary information

Once the data is in nparray format, we can apply any operations. Treating the nparray data as n-dimension matrices.
When we are done working with the data (doing data cleansing & transformation for example), we can convert the data (in nparray format) back to image format. 

In [2]:
from numpy import asarray

data = asarray(img)

print('data type: ', type(data))
print('data shape: ', data.shape)

data type:  <class 'numpy.ndarray'>
data shape:  (183, 275, 3)


In [3]:
#print the data

print(data)

[[[120 125 145]
  [120 125 145]
  [121 126 146]
  ...
  [ 65  65  67]
  [ 67  67  69]
  [ 70  70  72]]

 [[120 125 145]
  [120 125 145]
  [121 126 146]
  ...
  [ 65  65  67]
  [ 67  67  69]
  [ 70  70  72]]

 [[119 124 144]
  [120 125 145]
  [120 125 145]
  ...
  [ 64  64  66]
  [ 66  66  68]
  [ 70  70  72]]

 ...

 [[110 116 138]
  [110 116 138]
  [111 117 141]
  ...
  [ 79  81  93]
  [ 79  81  93]
  [ 78  80  92]]

 [[109 115 137]
  [110 116 138]
  [110 116 140]
  ...
  [ 79  81  93]
  [ 79  81  93]
  [ 78  80  92]]

 [[109 115 137]
  [109 115 137]
  [110 116 140]
  ...
  [ 79  81  93]
  [ 79  81  93]
  [ 78  80  92]]]


## CONVERT NP ARRAY back to IMAGE format

In [4]:
img_fromnparray = Image.fromarray(data)

img_fromnparray.show()

print('Image size: ', img_fromnparray.size)
print('Image format: ', img_fromnparray.format)
print('Image mode: ', img_fromnparray.mode)

Image size:  (275, 183)
Image format:  None
Image mode:  RGB


## SAVE the IMAGE to ANOTHER FORMAT, e.g. PNG (source was JPG before)

    1) 1st reopen image, and save is as PNG  
    2) 2nd reopen image and convert it to grey, and save is as PNG

In [5]:
data = asarray(Image.open(FilePath))
print("Saving as PNG (RGB)...",  "Image Processing/rose")

print(type(data), data.shape)

img_png = Image.fromarray(data).save('rose' + '-rgb' + '.png')


data = asarray(Image.open(FilePath).convert('L'))
print("Saving as PNG (Grey)...", "Image Processing/rose")

print(type(data), data.shape)

img_png = Image.fromarray(data).save('rose' + '-grey' + '.png')

Saving as PNG (RGB)... Image Processing/rose
<class 'numpy.ndarray'> (183, 275, 3)
Saving as PNG (Grey)... Image Processing/rose
<class 'numpy.ndarray'> (183, 275)
